[tasks.run]
description = "Run the reflex app locally"
run = "reflex run"
alias = "r"

[tasks.install]
description = "Install all dependencies"
run = """
#!/bin/bash
rye sync
cp requirements.lock requirements.txt
"""
alias = "i"

[tasks.build]
description = "Build the docker container"
run = "docker build -t lastfm-stats:latest ."
alias = "b"
depends = ["install"]

[tasks.start]
description = "Start the docker container"
run = "docker run -it --rm -p 3000:3000 -p 8000:8000 --name lastfm lastfm-stats:latest"
# run = "docker run -d -p 3000:3000 -p 8000:8000 --name lastfm reflex-lastfm:latest"
alias = "s"
