[tasks.run]
description = "Run the reflex app locally"
run = "uv run reflex run"
alias = "r"

[tasks.install]
description = "Install all dependencies"
run = """
#!/bin/bash
uv sync
uv export --no-dev --no-emit-project >requirements.txt
"""
alias = "i"

[tasks.build]
description = "Build the docker container"
run = "docker build -t ghcr.io/engeir/lastfm-stats:latest ."
alias = "b"
depends = ["install"]

[tasks.start]
description = "Start the docker container"
run = "docker run --env-file .env -it --rm -p 3000:3000 -p 8000:8000 --detach --name lastfm-stats ghcr.io/engeir/lastfm-stats:latest"
alias = "s"

[tasks.push]
description = "Push image to GitHub Container Registry"
run = "docker push ghcr.io/engeir/lastfm-stats:latest"
alias = "p"
