[tools]
python = { version = "3.11", virtualenv = ".venv" }

[tasks.run]
description = "Run the app (reflex)"
run = "reflex run"
alias = "r"

[tasks.install]
description = "Install all dependencies"
run = "poetry install"
alias = "i"
