on:
  push:
    branches:
      - main

permissions:
  contents: write
  contents: read
  packages: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: python
          package-name: lastfm
          extra-files: |
            README.md
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"style","section":"Styles","hidden":false},{"type":"refactor","section":"Code Refactoring","hidden":false},{"type":"perf","section":"Performance","hidden":false},{"type":"test","section":"Tests","hidden":false},{"type":"ci","section":"Continuous Integration","hidden":false},{"type":"build","section":"Build System","hidden":false},{"type":"docs","section":"Documentation","hidden":false}]'

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Docker build and push
        if: ${{ steps.release.outputs.release_created }}
        run: |
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GHCR }}
          docker login ghcr.io -u engeir -p ${{ secrets.DOCKER_GHCR }}
          docker build -t ghcr.io/engeir/lastfm-stats:${{ steps.release.outputs.tag_name }} .
          docker push ghcr.io/engeir/lastfm-stats:${{ steps.release.outputs.tag_name }}
